apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: 'app-staging'
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: "us-central1-docker.pkg.dev/core-stronghold-357120/helloworld-cloudrunpipeline/helloworld-cloudrunpipeline"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
    spec:
      containers:
      - name: 'helloworld-cloudrunpipeline'
        image: "us-central1-docker.pkg.dev/core-stronghold-357120/helloworld-cloudrunpipeline/helloworld-cloudrunpipeline"
        env:
          - name: 'TARGET'
            value: 'Staging'