apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: 'app-dev'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
    spec:
      containers:
      - name: 'helloworld-cloudrunpipeline'
        image: ${{ env.CONTAINER_IMAGE }}
        env:
          - name: 'TARGET'
            value: 'Dev'