apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: 'app-dev'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
    spec:
      containers:
      - name: 'app'
        image: us-central1-docker.pkg.dev/core-stronghold-357120/core-stronghold-357120-app-image-repo/helloworld-cloudrunpipeline
        env:
          - name: 'TARGET'
            value: 'Dev'