apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: 'helloworld-cloudrunpipeline'
description: 'Deployment pipeline for demo app'
serialPipeline:
  stages:
    - targetId: 'Dev'
      profiles: ['Dev']
    - targetId: 'Staging'
      profiles: ['Staging']
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'dev'
description: 'dev target'

run:
  location: 'projects/${PROJECT_ID_Target}/locations/${REGION}'
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'staging'
description: 'staging target'
run:
  location: 'projects/${PROJECT_ID}/locations/${REGION}'