apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: 'helloworld-cloudrunpipeline'
description: 'Deployment pipeline for demo app'
serialPipeline:
  stages:
    - targetId: 'dev'
      profiles: ['dev']
      strategy:
        standard:
          verify: true
          postdeploy:
            actions: ["postdeploy-action"] 
    - targetId: 'staging'
      profiles: ['staging']
      # strategy:
      #   standard:
      #     #verify: true
      #     postdeploy:
      #       actions: ["postdeploy-action"] 
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'dev'
description: 'dev target'
run:
  location: 'projects/core-stronghold-357120/locations/us-central1'
executionConfigs:
- usages:
  - RENDER
  - PREDEPLOY
  - DEPLOY 
  - VERIFY 
  - POSTDEPLOY
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'staging'
description: 'staging target'
run:
  location: 'projects/amishajhanjiproject1/locations/us-central1'
# executionConfigs:
# - usages:
#   - RENDER
#   - PREDEPLOY
#   - DEPLOY 
#   - VERIFY 
#   - POSTDEPLOY
