apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: 'helloworld-cloudrunpipeline3'
description: 'Deployment pipeline for demo app'
serialPipeline:
  stages:
    - targetId: 'dev'
      profiles: ['dev']
      strategy:
        standard:
          verify: true
    - targetId: 'staging'
      profiles: ['staging']
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'dev'
description: 'dev target'
run:
  location: 'projects/core-stronghold-357120/locations/us-central1'
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'staging'
description: 'staging target'
run:
  location: 'projects/amishajhanjiproject1/locations/us-central1'