apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: 'app'
deploy:
  cloudrun: {}
# build:
#   tagPolicy:
#     sha256: {}
  # artifacts:
  # - image: "us-central1-docker.pkg.dev/core-stronghold-357120/helloworld-cloudrunpipeline/helloworld-cloudrunpipeline"
profiles:
  - name: 'dev'
    manifests:
      rawYaml:
        - 'app-dev.yaml'
  - name: 'staging'
    manifests:
      rawYaml:
        - 'app-staging.yaml'