apiVersion: skaffold/v4beta5
kind: Config
customActions:
    - name: postdeploy-action
      containers:
      - name: postdeploy-echo
        image: us-central1-docker.pkg.dev/core-stronghold-357120/core-stronghold-357120-app-image-repo/helloworld
        command: ["npm run"]
        
metadata:
  name: 'app'
deploy:
  cloudrun: {}
profiles:
  - name: 'dev'
    manifests:
      rawYaml:
        - 'app-dev.yaml'
    verify:
      - name: verify-dev
        container:
          name: verify_test
          image: us-central1-docker.pkg.dev/core-stronghold-357120/core-stronghold-357120-app-image-repo/helloworld
          command: 
            [
              "echo 'hello world'"
            ]
  
  - name: 'staging'
    manifests:
      rawYaml:
        - 'app-staging.yaml'
    # verify:
    #   - name: verify-dev
    #     container:
    #       name: verify_test
    #       image: us-central1-docker.pkg.dev/core-stronghold-357120/core-stronghold-357120-app-image-repo/helloworld
    #       command: 
    #         [
    #           "echo 'hello world'"
    #         ]
  
