# apiVersion: skaffold/v3alpha1
# kind: Config
# metadata:
#   name: test-hello-world
# build:
#   tagPolicy:
#     sha256: {}
#   artifacts:
#   - image: us-central1-docker.pkg.dev/core-stronghold-357120/core-stronghold-357120-app-image-repo/helloworld-cloudrunpipeline
#     context: .
#     buildpacks:
#       builder: gcr.io/buildpacks/builder:v1
# profiles:
# - name: cloudbuild
#   build:
#     googleCloudBuild: {}
# manifests:
#   rawYaml:
#   - service.yaml
# deploy:
#   cloudrun:
#     region: us-central1 hh

apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: 'app'
deploy:
  cloudrun: {}
profiles:
  - name: 'Dev'
    manifests:
      rawYaml:
        - 'app-dev.template.yaml'
  - name: 'Staging'
    manifests:
      rawYaml:
        - 'app-staging.template.yaml'